### ISSUE TITLE
Update to 0.2.0

### ISSUE THREAD

**Issue by hmacdope** [conda-forge/solvation_analysis-feedstock#1]
### Comment:

@orionarcher this is where we update the recipie. 

The general flow is. 

1. Upload the tagged version to PyPi
2. Make a  **fork** (important) of this repo
4. update the recipie in `/recipe/meta.yaml` to pull the correct version and `SHA` in a branch on your fork. You should generally only need to change `meta.yaml`
5. PR against this repo
6. In the PR rerender with a bot command, I think its `@conda-forge-admin, please rerender `
7. Check CI passes and then merge.

**Comment by orionarcher** [comment]
Ok got it, thanks so much. Will update soon.

**Comment by hmacdope** [comment]
We are past 0.2.0 closing.
